//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CmfChileEntities : DbContext
    {
        public CmfChileEntities()
            : base("name=CmfChileEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ListadoDirectores> ListadoDirectores { get; set; }
        public virtual DbSet<ListadoFiscalizados> ListadoFiscalizados { get; set; }
    
        public virtual int ClearTables()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ClearTables");
        }
    }
}
