//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListadoDirectores
    {
        public long IdListadoDirectores { get; set; }
        public Nullable<long> IdListadoFiscalizados { get; set; }
        public Nullable<System.DateTime> DateScraping { get; set; }
        public string Rut { get; set; }
        public string Nombre { get; set; }
        public string Cargo { get; set; }
        public string FechaNombramiento { get; set; }
    
        public virtual ListadoFiscalizados ListadoFiscalizados { get; set; }
    }
}
