//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListadoFiscalizados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ListadoFiscalizados()
        {
            this.ListadoDirectores = new HashSet<ListadoDirectores>();
        }
    
        public long IdListadoFiscalizados { get; set; }
        public Nullable<System.DateTime> DateScraping { get; set; }
        public string Rut { get; set; }
        public string Entidad { get; set; }
        public string Estado { get; set; }
        public string UrlRegistroDirector { get; set; }
        public string UrlListadoEmisor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListadoDirectores> ListadoDirectores { get; set; }
    }
}
